{
 "title": "Statistiques Hôpital Donanam",
 "refresh": "5s",
 "panels": [
  {
   "title": "Patients Totaux (tous services)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(patients_total)" }
   ]
  },
  {
   "title": "Patients - Radiologie",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "patients_total{service=\"radiologie\"}"
    }
   ]
  },
  {
   "title": "Évolution des Patients par Service",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(patients_total[1m])" }
   ]
  }
 ]
}