# Dockerfile.streamlit

FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt requirements.txt
COPY app/ ./app/
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ .  

CMD ["streamlit", "run", "dashboard.py", "--server.enableCORS=false", "--server.address=0.0.0.0"]
