# global:
#   scrape_interval: 5s

# scrape_configs:
#   - job_name: "hopital_app"
#     static_configs:
#       - targets: ["app:8000"]

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb-exporter:9216"]
    metrics_path: "/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
