# global:
#   scrape_interval: 5s

# scrape_configs:
#   - job_name: "hopital_app"
#     static_configs:
#       - targets: ["app:8000"]

global:
  scrape_interval: 15s

# scrape_configs:
#   - job_name: "mongodb"
#     static_configs:
#       - targets: ["mongodb-exporter:9216"]

scrape_configs:
  - job_name: "hopital_app"
    static_configs:
      - targets: ["hopital_app:8000"]
